[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.33"
evm_version = "paris"
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read", path = "./configs" }]

[profile.default.fmt]
line_length = 120
tab_width = 4
bracket_spacing = false

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
